name: influxenterprise
director_uuid: <%= `bosh status --uuid` %>

releases:
- name: influxenterprise
  version: latest

jobs:

- name: influxdb-data
  template: influxdb-data
  instances: 2
  resource_pool: influx-resource-pool
  networks:
    - name: influx-network
      static_ips:
        - 10.244.10.5
        - 10.244.10.6
- name: influxdb-meta
  template: influxdb-meta
  instances: 3
  resource_pool: influx-resource-pool
  networks:
    - name: influx-network
      static_ips:
        - 10.244.10.2
        - 10.244.10.3
        - 10.244.10.4
- name: influxdb-web
  template: influxdb-web
  instances: 1
  resource_pool: influx-resource-pool
  networks:
    - name: influx-network
      static_ips:
        - 10.244.10.7

resource_pools:
- name: influx-resource-pool
  network: influx-network
  size: 1
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest
  cloud_properties: {}
#    name: random

networks:
- name: influx-network
  type: manual
  subnets:
  - range: 10.244.10.0/24
    gateway: 10.244.10.1
    static:
      - 10.244.10.2
      - 10.244.10.3
      - 10.244.10.4
      - 10.244.10.5
      - 10.244.10.6
      - 10.244.10.7
    cloud_properties: {}
#      name: random

compilation:
  workers: 6
  network: influx-network
  reuse_compilation_vms: true
  cloud_properties: {}
#    name: random


update:
  canaries: 1
  canary_watch_time: 30000-240000
  update_watch_time: 30000-600000
  max_in_flight: 3

properties:
  influxdb-web:
    database: sqlite3:///var/vcap/store/influxdb/enterprise.db
  influxdb:
    license-key: 82117eb1-57a5-4de4-802d-5856bf4a67b3
    shared-secret: "Long pass phrase that will be used to sign tokens"
  influxdbcluster:
    influxdb-meta:
      - 10.244.10.2
      - 10.244.10.3
      - 10.244.10.4
    influxdb-data:
      - 10.244.10.5
      - 10.244.10.6
    influxdb-web: 10.244.10.7
