---
platform: linux

image: docker:///teamidefix/maintanance

inputs:
- name: pipeline-repo
  path: .

run:
  path: pipeline/scripts/check-certs.sh

params:
  CERTS_TO_CHECK: url1:443,url2:4443
  VO_API_KEY: victorops-api-key
  VO_ROUTING_KEY: victorops-routing-key
