---
platform: linux

image: docker:///teamidefix/maintanance

inputs:
- name: pipeline-repo
  path: .

run:
  path: ./pipeline/scripts/check_domains.rb

params:
        CF_API:
        CF_USER:
        CF_PASSWORD:
        DOMAIN:
        DOMAIN_GUID:
        ALLOWED_ROUTES:
        VO_API_KEY:
        VO_ROUTING_KEY:
