meta:
  environment: influxenterprise-warden

  stemcell:
    name: bosh-warden-boshlite-ubuntu
    version: latest

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

jobs:
  - name: influxenterprise
    networks:
      - name: influxenterprise1

  - name: influxdb-data
    instances: 2
    networks:
      - name: influx-network
        static_ips: (( static_ips(3, 4) ))
  - name: influxdb-meta
    instances: 3
    networks:
      - name: influx-network
        static_ips: (( static_ips(0, 1, 2) ))
  - name: influxdb-web
    instances: 1
    networks:
      - name: influx-network
        static_ips: (( static_ips(5) ))

compilation:
  cloud_properties:
    name: random

resource_pools:
#  - name: small_z1
#    cloud_properties:
#      name: random
  - name: influx-resource-pool
    cloud_properties:
      name: random


# properties:
#   influxdb-web:
#     database: sqlite3:///var/vcap/store/influxdb/enterprise.db
#   influxdb:
#     license-key: 82117eb1-57a5-4de4-802d-5856bf4a67b3
#     shared-secret: "Long pass phrase that will be used to sign tokens"
#   influxdbcluster:
#     influxdb-meta: (( networks.influx-network.static_ips(0, 1, 2) ))
#     influxdb-data: (( networks.influx-network.static_ips(3, 4) ))
#     influxdb-web: (( networks.influx-network.static_ips(5) ))

networks:
- name: influx-network
  type: manual
  subnets:
  - range: 10.244.38.0/28
    gateway: 10.244.38.1
    static:
      - 10.244.38.2
      - 10.244.38.3
      - 10.244.38.4
      - 10.244.38.5
      - 10.244.38.6
      - 10.244.38.7
      - 10.244.38.8
    cloud_properties:
      name: random



# - name: influxenterprise1
#   # Assumes up to 5 VMs, including 1 static and 4 dynamic.
#   # Plus 5 (double the size) unused IPs, due to BOSH bug/quirk.
#   subnets:
#   - cloud_properties:
#       name: random
#     range: 10.244.2.0/30
#     reserved:
#     - 10.244.2.1
#     static:
#     - 10.244.2.2
#
#   - cloud_properties:
#       name: random
#     range: 10.244.2.4/30
#     reserved:
#     - 10.244.2.5
#     static: []
#   - cloud_properties:
#       name: random
#     range: 10.244.2.8/30
#     reserved:
#     - 10.244.2.9
#     static: []
#   - cloud_properties:
#       name: random
#     range: 10.244.2.12/30
#     reserved:
#     - 10.244.2.13
#     static: []
#   - cloud_properties:
#       name: random
#     range: 10.244.2.16/30
#     reserved:
#     - 10.244.2.17
#     static: []
#
#   # Bonus double-sized network required due to BOSH oddity
#   - cloud_properties:
#       name: random
#     range: 10.244.2.20/30
#     reserved:
#     - 10.244.2.21
#     static: []
#   - cloud_properties:
#       name: random
#     range: 10.244.2.24/30
#     reserved:
#     - 10.244.2.25
#     static: []
#   - cloud_properties:
#       name: random
#     range: 10.244.2.28/30
#     reserved:
#     - 10.244.2.29
#     static: []
#   - cloud_properties:
#       name: random
#     range: 10.244.2.32/30
#     reserved:
#     - 10.244.2.33
#     static: []
#   - cloud_properties:
#       name: random
#     range: 10.244.2.36/30
#     reserved:
#     - 10.244.2.37
#     static: []
