meta:
  environment: ~

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 1000-15000
  update_watch_time: 1000-15000
  serial: true

jobs:
  - name: influxdb-data
    template: influxdb-data
    instances: 2
    resource_pool: influx-resource-pool
    networks: (( merge ))
    persistent_disk: 0
    properties: {}

  - name: influxdb-meta
    template: influxdb-meta
    instances: 3
    resource_pool: influx-resource-pool
    networks: (( merge ))
    persistent_disk: 0
    properties: {}

  - name: influxdb-web
    template: influxdb-web
    instances: 1
    resource_pool: influx-resource-pool
    networks: (( merge ))

networks: (( merge ))

properties:
  influxdb-web:
    database: sqlite3:///var/vcap/store/influxdb/enterprise.db
    smtp-host: localhost
    smtp-port: 25
    smtp-username: ""
    smtp-password: ""
    smtp-fromemail: team-idefix@sap.com

  influxdb:

  influxdbcluster:
    influxdb-meta: (( jobs.influxdb-meta.networks.influx-network.static_ips ))
    influxdb-data: (( jobs.influxdb-data.networks.influx-network.static_ips ))
    influxdb-web: (( jobs.influxdb-web.networks.influx-network.static_ips ))
